# Generated by Django 4.1.7 on 2023-03-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galery", "0002_photography_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photography",
            name="category",
            field=models.CharField(
                choices=[
                    ("Nebulosa", "Nebulosa"),
                    ("Estrela", "Estrela"),
                    ("Galáxia", "Galáxia"),
                    ("Planeta", "Planeta"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
