# Generated by Django 4.1.7 on 2023-03-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galery", "0003_alter_photography_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="photography",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
