# Generated by Django 4.1.7 on 2023-03-09 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galery", "0004_photography_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="photography",
            name="published_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
